from distutils.core import setup

setup(name="CTPy",
      version="1.0.1",
      packages=['ctpy',
                'ctpy.math',
                'ctpy.coarsegraining',
                'ctpy.data',
                'ctpy.innovation_models',
                'ctpy.strategies',
                'ctpy.utils'],
      scripts=['simulations/neutral-kn-interactive.py',
               'simulations/neutral-kn-sweep.py',
               'analytics/classify_individual_samples.py',
               'analytics/classify_individual_samples_worker.py',
               'admin/construct_classifications.py',
               'admin/simulation_planning.py',
               'admin/subsample_individual_samples.py',
               ],
      author='Mark E. Madsen',
      author_email='mark@madsenlab.org',
      url='https://github.com/mmadsen/',
      classifiers=[
          'Development Status :: 3 - Alpha',
          'Environment :: Console',
          'Intended Audience :: Science/Research',
          'License :: OSI Approved :: Apache Software License',
          'Operating System :: POSIX',
          'Programming Language :: Python :: 2.7',
          'Topic :: Scientific/Engineering',
      ]
      )