.TH "admin Directory Reference" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
admin Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconstruct_classifications\&.py\fP"
.br
.ti -1c
.RI "file \fBexport_data_to_csv\&.py\fP"
.br
.ti -1c
.RI "file \fBgen_parameter_document\&.py\fP"
.br
.ti -1c
.RI "file \fBinitialize_experiment\&.py\fP"
.br
.ti -1c
.RI "file \fBmodify_experiment_tracking\&.py\fP"
.br
.ti -1c
.RI "file \fBsimulation_planning\&.py\fP"
.br
.ti -1c
.RI "file \fBtheta-combinations\&.py\fP"
.br
.in -1c
