.TH "simulations Directory Reference" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simulations Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbasic-axelrod\&.py\fP"
.br
.ti -1c
.RI "file \fBneutral-kn-interactive\&.py\fP"
.br
.ti -1c
.RI "file \fBneutral-kn-sweep\&.py\fP"
.br
.in -1c
