.TH "ctpy Directory Reference" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctpy Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcoarsegraining\fP"
.br
.ti -1c
.RI "directory \fBdata\fP"
.br
.ti -1c
.RI "directory \fBinnovation_models\fP"
.br
.ti -1c
.RI "directory \fBmath\fP"
.br
.ti -1c
.RI "directory \fBstrategies\fP"
.br
.ti -1c
.RI "directory \fButils\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.in -1c
