.TH "test Directory Reference" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtest_allele_distribution\&.py\fP"
.br
.ti -1c
.RI "file \fBtest_configuration\&.py\fP"
.br
.ti -1c
.RI "file \fBtest_dimension_mode_creation\&.py\fP"
.br
.ti -1c
.RI "file \fBtest_innovation_interval_stats\&.py\fP"
.br
.ti -1c
.RI "file \fBtest_math\&.py\fP"
.br
.ti -1c
.RI "file \fBtest_sampling\&.py\fP"
.br
.ti -1c
.RI "file \fBtest_update_data\&.py\fP"
.br
.in -1c
