.TH "ctpy/data Directory Reference" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctpy/data Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBclassification_data\&.py\fP"
.br
.ti -1c
.RI "file \fBclassification_mode_definitions\&.py\fP"
.br
.ti -1c
.RI "file \fBexperiment_tracking\&.py\fP"
.br
.ti -1c
.RI "file \fBindividual_sample\&.py\fP"
.br
.ti -1c
.RI "file \fBindividual_sample_classified\&.py\fP"
.br
.ti -1c
.RI "file \fBindividual_sample_fulldataset\&.py\fP"
.br
.ti -1c
.RI "file \fBpergeneration_stats_postclassification\&.py\fP"
.br
.ti -1c
.RI "file \fBpergeneration_stats_traits\&.py\fP"
.br
.ti -1c
.RI "file \fBpersimrun_stats_postclassification\&.py\fP"
.br
.ti -1c
.RI "file \fBrichness_population\&.py\fP"
.br
.ti -1c
.RI "file \fBrichness_sample\&.py\fP"
.br
.ti -1c
.RI "file \fBsimulation_data\&.py\fP"
.br
.ti -1c
.RI "file \fBtrait_count_population\&.py\fP"
.br
.ti -1c
.RI "file \fBtrait_count_sample\&.py\fP"
.br
.ti -1c
.RI "file \fBtrait_lifetime\&.py\fP"
.br
.in -1c
