.TH "ctpy.data.classification_mode_definitions.ClassificationModeDefinitions" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctpy.data.classification_mode_definitions.ClassificationModeDefinitions \- 
.PP
A classification dimension is defined by a set of modes which partition the space of the dimension\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Document\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB__mongometa__\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A classification dimension is defined by a set of modes which partition the space of the dimension\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CTPy from the source code\&.
