.TH "ctpy.data.classification_data.ClassificationData" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctpy.data.classification_data.ClassificationData \- 
.PP
A classification is represented by a dict of dimensions, each of which points to a mode definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Document\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB__mongometa__\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBclassification_type\fP = Field(str)"
.br
.ti -1c
.RI "tuple \fBmaxalleles\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBdimensions\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBmean_coarseness\fP = Field(float)"
.br
.ti -1c
.RI "tuple \fBmodes_for_dimensions\fP = Field([schema\&.ObjectId])"
.br
.in -1c
.SH "Detailed Description"
.PP 
A classification is represented by a dict of dimensions, each of which points to a mode definition\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for CTPy from the source code\&.
