.TH "ctpy.data.pergeneration_stats_traits.PerGenerationStatsTraits.__mongometa__" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctpy.data.pergeneration_stats_traits.PerGenerationStatsTraits.__mongometa__ \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBsession\fP = Session\&.by_name(_get_dataobj_id())"
.br
.ti -1c
.RI "string \fBname\fP = 'pergeneration_stats_traits'"
.br
.ti -1c
.RI "tuple \fBsimulation_run_id\fP = Field(str)"
.br
.ti -1c
.RI "tuple \fBsimulation_time\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBreplication\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBsample_size\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBpopulation_size\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBmutation_rate\fP = Field(float)"
.br
.ti -1c
.RI "tuple \fBdimensionality\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBmean_trait_richness\fP = Field(float)"
.br
.ti -1c
.RI "tuple \fBmean_evenness_shannon_entropy\fP = Field(float)"
.br
.ti -1c
.RI "tuple \fBmean_evenness_iqv\fP = Field(float)"
.br
.ti -1c
.RI "tuple \fBloci_trait_richness\fP = Field([int])"
.br
.ti -1c
.RI "tuple \fBloci_evenness_shannon_entropy\fP = Field([float])"
.br
.ti -1c
.RI "tuple \fBloci_evenness_iqv\fP = Field([float])"
.br
.ti -1c
.RI "tuple \fBloci_neutrality_slatkin\fP = Field([float])"
.br
.ti -1c
.RI "tuple \fBmean_neutrality_slatkin\fP = Field(float)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CTPy from the source code\&.
