.TH "ctpy.utils.script_args.ScriptArgs" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctpy.utils.script_args.ScriptArgs \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBexperiment_name\fP"
.br
.ti -1c
.RI "\fBdatabase_hostname\fP"
.br
.ti -1c
.RI "\fBdatabase_port\fP"
.br
.ti -1c
.RI "\fBclassification_list\fP"
.br
.ti -1c
.RI "\fBparallelization\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBdebug\fP = False"
.br
.ti -1c
.RI "string \fBexperiment_name\fP = 'default'"
.br
.ti -1c
.RI "string \fBdatabase_hostname\fP = 'localhost'"
.br
.ti -1c
.RI "string \fBdatabase_port\fP = '27017'"
.br
.ti -1c
.RI "list \fBclassification_list\fP = []"
.br
.ti -1c
.RI "int \fBparallelization\fP = 5"
.br
.ti -1c
.RI "\fBconfiguration\fP = None"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CTPy from the source code\&.
