.TH "ctpy.data.simulation_data.SimulationRun" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctpy.data.simulation_data.SimulationRun \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Document\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB__mongometa__\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBscript_filename\fP = Field(str)"
.br
.ti -1c
.RI "tuple \fBreplicates\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBnum_loci\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBsample_size\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBpopulation_size\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBmutation_rate\fP = Field(float)"
.br
.ti -1c
.RI "tuple \fBsimulation_run_id\fP = Field(str)"
.br
.ti -1c
.RI "tuple \fBnum_initial_alleles\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBmax_alleles\fP = Field(int)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CTPy from the source code\&.
