.TH "ctpy.data.pergeneration_stats_traits.PerGenerationStatsTraits" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctpy.data.pergeneration_stats_traits.PerGenerationStatsTraits \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Document\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB__mongometa__\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CTPy from the source code\&.
