.TH "ctpy.strategies.conformism.ConformistMatingScheme" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctpy.strategies.conformism.ConformistMatingScheme \- 
.PP
A homogeneous mating scheme which implements a variety of 'conformist' transmission rules\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits HomoMating\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBprobSelectParentWithMostPopularTraits\fP"
.br
.RI "\fISelects parents with the 'most popular' traits, with probability\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A homogeneous mating scheme which implements a variety of 'conformist' transmission rules\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CTPy from the source code\&.
