.TH "ctpy.strategies.conformism" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctpy.strategies.conformism \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConformistMatingScheme\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The conformism module contains a variety of methods for implementing a 'conformist'
strategy for cultural transmission.  Each is implemented as a simuPOP PyParentsChooser
operator, which can then be used to define a custom mating scheme.  This allows one to
use the standard offspring generators to form the next generation, across subpopulations.

Some of the strategies are conditional, and thus have parameters that need to be set.  An
example would be the standard Bentley/Mesoudi/Lycett implementation of conformism, in which
with probability p, we choose the most frequent trait in the population (or subpopulation),
and with probability 1-p, we select a parent randomly.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for CTPy from the source code\&.
