.TH "ctpy.innovation_models.simple_mutators.KAlleleLifetimeTrackingMutator" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctpy.innovation_models.simple_mutators.KAlleleLifetimeTrackingMutator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits PyOperator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBmutate\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBk\fP"
.br
.ti -1c
.RI "\fBrates\fP"
.br
.ti -1c
.RI "\fBloci\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CTPy from the source code\&.
