.TH "ctpy.utils.configuration.CTPyConfiguration" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctpy.utils.configuration.CTPyConfiguration \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__repr__\fP"
.br
.ti -1c
.RI "def \fBto_latex_table\fP"
.br
.RI "\fIConstructs a LaTeX table and tabular environment for the simulation parameters and control variable settings\&. \fP"
.ti -1c
.RI "def \fBto_pandoc_table\fP"
.br
.RI "\fIConstructs a Markdown table (in pandoc format) for the simulation parameters and control variable settings\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconfig\fP"
.br
.ti -1c
.RI "\fBNUM_SAMPLES_ANALYZED_PER_FINAL_SAMPLE_PATH\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBMODETYPE_EVEN\fP = str('EVEN')"
.br
.ti -1c
.RI "tuple \fBMODETYPE_RANDOM\fP = str('RANDOM')"
.br
.ti -1c
.RI "int \fBSLATKIN_MONTECARLO_REPLICATES\fP = 10000"
.br
.ti -1c
.RI "int \fBMAXALLELES\fP = 1000000000"
.br
.RI "\fIResearch-level constants\&. \fP"
.ti -1c
.RI "int \fBNUM_REPLICATES_FOR_RANDOM_DIMENSION_MODES\fP = 10"
.br
.ti -1c
.RI "list \fBDIMENSION_PARTITIONS\fP = [2,3,4,8,16,32]"
.br
.ti -1c
.RI "list \fBDIMENSIONS_STUDIED\fP = [2,3,4,6,8]"
.br
.ti -1c
.RI "list \fBINNOVATION_RATES_STUDIED\fP = [0\&.0001,0\&.00025,0\&.0005,0\&.001,0\&.0025,0\&.005,0\&.01,0\&.025]"
.br
.ti -1c
.RI "int \fBSIMULATION_LENGTH_AFTER_STATIONARITY\fP = 10000"
.br
.ti -1c
.RI "list \fBTIME_AVERAGING_DURATIONS_STUDIED\fP = [1000,500,250,125,63,32,16,8,1]"
.br
.ti -1c
.RI "int \fBINITIAL_TRAIT_NUMBER\fP = 10"
.br
.ti -1c
.RI "int \fBSAMPLING_INTERVAL\fP = 1"
.br
.ti -1c
.RI "int \fBREPLICATIONS_PER_PARAM_SET\fP = 10"
.br
.ti -1c
.RI "list \fBSAMPLE_SIZES_STUDIED\fP = [25,50,100,200]"
.br
.ti -1c
.RI "list \fBPOPULATION_SIZES_STUDIED\fP = [500,1000,2500,5000]"
.br
.ti -1c
.RI "list \fBDEME_NUMBERS_STUDIED\fP = [32]"
.br
.ti -1c
.RI "int \fBNUMBER_RANDOM_MIGRATION_MATRICES_STUDIED\fP = 10"
.br
.ti -1c
.RI "list \fBDENSITY_SMALL_WORLD_LINKS_STUDIED\fP = [0\&.0,0\&.1,0\&.25,0\&.5,0\&.75]"
.br
.ti -1c
.RI "list \fBCLUSTERING_COEFFICIENTS_STUDIED\fP = [0\&.0,0\&.1,0\&.25,0\&.5,0\&.75]"
.br
.ti -1c
.RI "int \fBNUM_SAMPLES_ANALYZED_PER_FINAL_SAMPLE_PATH\fP = 1"
.br
.ti -1c
.RI "dictionary \fBparameter_labels\fP"
.br
.ti -1c
.RI "list \fBvars_to_filter\fP = ['config', 'TIME_AVERAGING_DURATIONS_STUDIED', 'MODETYPE_EVEN','MODETYPE_RANDOM','\fBMAXALLELES\fP','DEME_NUMBERS_STUDIED','NUMBER_RANDOM_MIGRATION_MATRICES_STUDIED','DENSITY_SMALL_WORLD_LINKS_STUDIED','CLUSTERING_COEFFICIENTS_STUDIED']"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def ctpy\&.utils\&.configuration\&.CTPyConfiguration\&.to_latex_table (self, experiment, kwargs)"

.PP
Constructs a LaTeX table and tabular environment for the simulation parameters and control variable settings\&. A list of 'internal' or unimplemented variables are filtered out of this list, and actual variable names are translated to human-readable phrases with a lookup table\&.
.PP
Takes an optional named argument: caption=String\&. This parameter will replace the caption automatically generated by this method\&.
.PP
:return: A string comprising the LaTeX representation for the parameters\&. 
.SS "def ctpy\&.utils\&.configuration\&.CTPyConfiguration\&.to_pandoc_table (self, experiment, kwargs)"

.PP
Constructs a Markdown table (in pandoc format) for the simulation parameters and control variable settings\&. A list of 'internal' or unimplemented variables are filtered out of this list, and actual variable names are translated to human-readable phrases with a lookup table\&.
.PP
:return: Text string representing a Pandoc table 
.SH "Member Data Documentation"
.PP 
.SS "dictionary ctpy\&.utils\&.configuration\&.CTPyConfiguration\&.parameter_labels\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
1 = {
2         'NUM_SAMPLES_ANALYZED_PER_FINAL_SAMPLE_PATH' : 'Num samples taken after stationarity, per run',
3         'POPULATION_SIZES_STUDIED' : 'Population sizes',
4         'SAMPLE_SIZES_STUDIED' : 'Sample sizes taken at each sampling interval',
5         'REPLICATIONS_PER_PARAM_SET' : 'Replicate simulation runs at each parameter combination',
6         'SAMPLING_INTERVAL' : 'Interval in generations for samples after stationarity',
7         'INITIAL_TRAIT_NUMBER' : 'Number of traits per dimension for initializing population',
8         'SIMULATION_LENGTH_AFTER_STATIONARITY' : 'Length of simulation run after stationarity',
9         'INNOVATION_RATES_STUDIED' : 'Innovation rates (event probability per person per generation)',
10         'DIMENSIONS_STUDIED' : 'Trait and classification dimensionalities',
11         'DIMENSION_PARTITIONS' : 'Classification coarseness levels (modes per dimension)',
12         'NUM_REPLICATES_FOR_RANDOM_DIMENSION_MODES' : 'Replicate random classifications per coarseness level',
13         'SLATKIN_MONTECARLO_REPLICATES' : 'Number of Monte Carlo replicates for Ewens-Slatkin neutrality test',
14     }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for CTPy from the source code\&.
