.TH "ctpy.data.individual_sample_fulldataset.IndividualSampleFullDataset.__mongometa__" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctpy.data.individual_sample_fulldataset.IndividualSampleFullDataset.__mongometa__ \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBsession\fP = Session\&.by_name(_get_dataobj_id())"
.br
.ti -1c
.RI "string \fBname\fP = 'individual_samples_fulldataset'"
.br
.ti -1c
.RI "tuple \fBsimulation_time\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBreplication\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBdimensionality\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBsample_size\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBpopulation_size\fP = Field(int)"
.br
.ti -1c
.RI "tuple \fBmutation_rate\fP = Field(float)"
.br
.ti -1c
.RI "tuple \fBsimulation_run_id\fP = Field(str)"
.br
.ti -1c
.RI "tuple \fBsample\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "tuple ctpy\&.data\&.individual_sample_fulldataset\&.IndividualSampleFullDataset\&.__mongometa__\&.sample\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
1 = Field([
2             dict(id=int, genotype=[int])
3         ])
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for CTPy from the source code\&.
