.TH "ctpy.data.richness_population.RichnessSample.__mongometa__" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctpy.data.richness_population.RichnessSample.__mongometa__ \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBsession\fP = Session\&.by_name(_get_dataobj_id())"
.br
.ti -1c
.RI "string \fBname\fP = 'richness_population'"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CTPy from the source code\&.
