.TH "test_allele_distribution.AlleleDistributionTest" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_allele_distribution.AlleleDistributionTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_uniform_10alleles\fP"
.br
.ti -1c
.RI "def \fBtest_uniform_5alleles\fP"
.br
.ti -1c
.RI "def \fBtest_uniform_3alleles\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CTPy from the source code\&.
