.TH "test_innovation_interval_stats.TestInnovationIntervalStats" 3 "Sun Oct 13 2013" "Version 1.0.3" "CTPy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_innovation_interval_stats.TestInnovationIntervalStats \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP"
.br
.ti -1c
.RI "def \fBtest_mean\fP"
.br
.ti -1c
.RI "def \fBtest_sd\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconfig\fP"
.br
.ti -1c
.RI "\fBtest_data\fP"
.br
.ti -1c
.RI "\fBexpected_intervals\fP"
.br
.ti -1c
.RI "\fBexpected_mean_interval\fP"
.br
.ti -1c
.RI "\fBexpected_sd_interval\fP"
.br
.ti -1c
.RI "\fBepsilon\fP"
.br
.ti -1c
.RI "\fBstats\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CTPy from the source code\&.
